### ISSUE TITLE
Explore the inclusion of `&self` as a parameter for `Circuit::configure()`

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2#106]
See this thread in halo2/zkevm-circuits: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/948#issuecomment-1331577880

There is discussed the fact that it's really painful to pass a lot of const-generics or the need to edit the `Config` type to tuples or similar stuff when you're implementing the `Circuit` trait simply because it doesn't have `&self` as parameter.

Would be nice to explore a bit how that would feel and if we encounter any unexpected issues with it.

**Comment by CPerezz** [comment]
Candidate to be discussed in the Halo2-call/Office hours

**Comment by han0110** [comment]
To use `halo2` as a backend, I think the approach with associated type looks good and it should be relatively easy to migrate.

Just note we might also change other APIs like:

- [`VerifyingKey::read`](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/plonk.rs#L101)
- [`VerifyingKey::from_bytes`](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/plonk.rs#L150)
- [`ProvingKey::read`](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/plonk.rs#L335)
- [`ProvingKey::from_bytes`](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/plonk.rs#L369)
- [`create_domain`](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/plonk/keygen.rs#L27)
- [`CircuitGates::collect`](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/dev/gates.rs#L106)

Because they don't take `circuit: &C` as an input, they just use the `C::configure` directly, so we might need to add an extra argument `param: C::Param` to make sure the configure is expected.

**Comment by ed255** [comment]
> Could you elaborate a bit more on the insights about why this will help to split halo2 into front and backend? And also on why does it provide so that DSLs are easier/possible to be implemented?

The interface that halo2 uses for the backend is the `Circuit` trait: anything that implements this trait can be used with the halo2 proving system.  But the `configure` method of this trait doesn't take `self` or any user provided arguments, and this method is the one that defines the columns, the polynomial identities and the lookup expressions.  Since this method is called like `Circuit::configure(meta)` it means that the configuration needs to be defined at compilation time, statically with hardcoded "rust code".  You can't encode the circuit into your own format and then convert it into a halo2 `Circuit`, because the `configure` doesn't have access to any user-defined runtime variables.  Right now everything needs to be defined inside the `configure` function, you can't have auxiliary data outside of it.  And for a DSL, before defining the `Circuit` we would process a higher level circuit definition, store it in variables and then we would want to pass it to the `configure` method of a generic `Circuit`.

Here's an example for Plaf, which uses the `configure(&self, ...)` approach.
There's a single type that implements `Circuit` and is generic to define any circuit you want which is encoded in the plaf format:
https://github.com/Dhole/polyexen/blob/ba36325e9dd18125c4c7e4e7e34ba8bb75dfa110/src/plaf/backends/halo2.rs#L171-L181

Without access to `self` or another user provided parameter, you need a new rust type for each circuit; each instance of that type will be the same circuit with different witness.  With access to `self` or another user provided parameter, you can have a single type and then each instance of that type is a different circuit.

**Comment by CPerezz** [comment]
Thanks for the insight @ed255 !

Makes complete sense. In favour for the change! Let's hear @han0110 and @kilic
