### ISSUE TITLE
Include `at_rows` variant for `assert_satisfied`

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2#133]
This should had been done when we fixed `prover.assert_satisfied`. We're missing this, and will be tach-debt generated in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1107 most probably.

**Comment by ed255** [comment]
I would like to suggest another small change to make things more flexible: declare `VerifyFailure.emit` as `pub` instead of `pub(crate)`; so that it can be called externally on the `VerifyFailure`s returned by all the `verify*` functions.

**Comment by CPerezz** [comment]
I mean, I can understand why is it `pub(crate)` on upstream. 
What do we gain from that? As if you want `emit` to be called you just need to use `assert_satisfied`. You say it because you don't want the fn to call the `panic`?

**Comment by ed255** [comment]
> I mean, I can understand why is it `pub(crate)` on upstream. What do we gain from that? 

It would give more control to the user of the library, and it removes the need to introduce 4 variations of `assert_satisfied`, which would be: `assert_satisfied`, `assert_satisfied_par`, `assert_satisfied_at_rows`, `assert_satisfied_at_rows_par`; because the user of the library could just call `error.emit(&prover)`.  But overall this is just a personal feeling; if we introduce `assert_satisfied_at_rows_par` I don't have any strong reason to ask for a `pub fn emit`.
