### ISSUE TITLE
Poseidon gadget dropping the initialised hasher

### ISSUE THREAD

**Issue by enricobottazzi** [privacy-scaling-explorations/halo2#165]
The problem is the hash function, as defined in [halo2_gadgets](https://github.com/privacy-scaling-explorations/halo2/blob/main/halo2_gadgets/src/poseidon/primitives.rs#L332) takes ownership of the initialized hasher and returns the output of the hashing function while dropping the hasher. This makes the initialized hasher not reusable for different hashes. 

Performance-wise the operation to initialize the hasher `init() takes around 2 seconds. It means every hashing operation performed takes 2 seconds at least. That's an unnecessary overhead in my opinion. 

I wonder if there's a specific design reason for that. Otherwise I could open a PR that simply adds the clone trait on the Hash struct allowing to reuse an initialized hasher across different hash operations.

More information related to the necessity of this for my specific use case [here](https://github.com/summa-dev/merkle-sum-tree-rust/pull/1)

FIXED: link to halo2_gadgets

**Comment by str4d** [comment]
> Performance-wise the operation to initialize the hasher `init() takes around 2 seconds. It means every hashing operation performed takes 2 seconds at least. That's an unnecessary overhead in my opinion.

That seems way slower than it should be 😕 I've looked over the relevant code (which I wrote) and assuming that you are using a hasher spec that has precomputed round constants and MDS, it should only be assigning initial state into the circuit. Can you provide more specific setup details and benchmarks?

As for adding `impl Clone for poseidon::Hash`, that _should_ be fine IIRC because domain-separation of the initial state is encoded into the type system. I'd be very wary of exposing an `impl Clone` for a partially-updated hasher because it might constrain the way a user would expect, but it looks like I made the `poseidon::Hash` gadget one-shot only, so `Clone` on that combined with `Hash::hash` being consuming should be fine. Feel free to open a PR for it on https://github.com/zcash/halo2.

**Comment by enricobottazzi** [comment]
Hi! Thanks for the quick reply! I actually linked to the wrong Hash struct, sorry about that. I was referring to this [hash struct](https://github.com/privacy-scaling-explorations/halo2/blob/main/halo2_gadgets/src/poseidon/primitives.rs#L332), which is the poseidon hash primitive. I'm using that outside of any circuit. Would it still be ok for you to add the `Clone` trait there?

Regarding the performance issue, I'm working on a M2 PRO 32GB. I benchmarked the operation of initializing the following hasher and it takes on average 1.3 seconds

```
pub fn poseidon(l1: Fp, l2: Fp, r1: Fp, r2: Fp) -> Fp {
    const WIDTH: usize = 5;
    const RATE: usize = 4;
    const L: usize = 4;

    let now = Instant::now();
    let hasher = poseidon::Hash::<_, MySpec<Fp, WIDTH, RATE>, ConstantLength<L>, WIDTH, RATE>::init();
    let elapsed = now.elapsed();
    println!("Elapsed: {:.2?}", elapsed);

    hasher.hash([l1, l2, r1, r2])
}
```

**Comment by jonathanpwang** [comment]
Is the gadget recomputing the round constants (in `Spec`) on each invocation? I've seen that happen in some other places, which really slows down the hashing.

**Comment by enricobottazzi** [comment]
@jonathanpwang yes, that's correct. That's because the hash function takes ownership of the hasher and later drops it, which makes it practically impossible to separate the hasher from the hash function.

https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_gadgets/src/poseidon/primitives.rs#L374-L382

**Comment by CPerezz** [comment]
@enricobottazzi can we actually close this? OR do you have a proposal to improve this aside from making the struct `Clone`?
