### ISSUE TITLE
The necessity of coset of roots of unity in FFT

### ISSUE THREAD

**Issue by autquis** [privacy-scaling-explorations/halo2#201]
Hello,

The current implementation considers a coset of roots of unity as the evaluation domain (i.e., $`\zeta \cdot \omega^i`$).

https://github.com/privacy-scaling-explorations/halo2/blob/fe71cd4647630d3af03d9cb72d301a431537974c/halo2_proofs/src/poly/domain.rs#L246-L248

1. I wonder what the necessity of this coset is.
2. Is it possible to add a function to the API that evaluates the polynomial on exactly the roots of unity?

**Comment by CPerezz** [comment]
Hey! I'm not  sure I do follow!

A coset is subset of mathematical group consisting of all the products obtained by multiplying fixed element of a group by each of elements of given subgroup.

In this case, the sub-group are all the roots of unity. So I'm not sure exactly what's the issue here.
Could you elaborate a bit more?

Also, maybe I'm missing something. So will cc: @davidnevadoc @han0110

**Comment by han0110** [comment]
> 1. I wonder what the necessity of this coset is.

IIUC the necessity of the coset is to avoid the "divide by 0" case, since `halo2` compute the quotient polynomial in evalation domain directly, we need to divde each evaluation by <code>t(X) = (X<sup>n</sup> − 1)</code>, which evaluates to `0` on roots of unity of the original domain.

With coset <code>t(δX) = ((δX)<sup>n</sup> − 1)</code> it then evaluates non-zero values. See also current impl of denominators precomputation:

https://github.com/privacy-scaling-explorations/halo2/blob/fe71cd4647630d3af03d9cb72d301a431537974c/halo2_proofs/src/poly/domain.rs#L87-L110

If we do the division on coefficient basis I think we don't need to move to coset, but for circuit has degree <code>2<sup>k</sup> + 1</code> will need to do FFT on `k + 1`-extended domain instead of `k`-extended domain. Not sure if I've missed other things that need the coset tho.

> 2. Is it possible to add a function to the API that evaluates the polynomial on exactly the roots of unity?

I think it should be doable, just don't call `distribute_powers_zeta` and choose `omega` and `k` you'd like to check.

https://github.com/privacy-scaling-explorations/halo2/blob/fe71cd4647630d3af03d9cb72d301a431537974c/halo2_proofs/src/poly/domain.rs#L240-L254
